CREATE TABLE `industry` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `sector_id` bigint NOT NULL,
  `creation_timestamp` datetime(6) DEFAULT NULL,
  `last_updated_timestamp` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `sector_id` (`sector_id`),
  CONSTRAINT `industry_ibfk_1` FOREIGN KEY (`sector_id`) REFERENCES `sector` (`id`)
) ENGINE=InnoDB ;

INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Agricultural Inputs', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Aluminum', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Building Materials', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Chemicals', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Cooking Coal', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Copper', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Gold', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Lumber & Wood Production', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Other Industrial Metals & Mining', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Other Precious Metals & Mining', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Paper & Paper Products', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Silver', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Specialty Chemicals', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Steel', 1);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Advertising Agencies', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Broadcasting', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Electronic Gaming & Multimedia', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Entertainment', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Internet Content & Information', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Publishing', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Telecom Services', 2);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Apparel Manufacturing', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Apparel Retail', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Auto & Truck Dealerships', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Auto Manufacturers', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Auto Parts', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Department Stores', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Footwear & Accessories', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Furnishings, Fixtures & Appliances', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Gambling', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Home Improvement Retail', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Internet Retail', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Leisure', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Lodging', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Luxury Goods', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Packaging & Containers', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Personal Services', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Recreational Vehicles', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Residential Construction', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Resorts & Casinos', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Restaurants', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Specialty Retail', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Textile Manufacturing', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Travel Services', 3);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Beverages - Brewers', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Beverages - Non-Alcoholic', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Beverages - Wineries & Distilleries', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Confectioners', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Discount Stores', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Education & Training Services', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Farm Products', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Food Distribution', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Grocery Stores', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Household & Personal Products', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Packaged Foods', 4);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Oil & Gas Drilling', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Oil & Gas E&P', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Oil & Gas Equipment & Services', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Oil & Gas Integrated', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Oil & Gas Midstream', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Oil & Gas Refining & Marketingobacco', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Thermal Coal', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Uranium', 5);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Asset Management', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Banks - Diversified', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Banks - Regional', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Capital Markets', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Credit Services', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Financial Conglomerates', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Financial Data & Stock Exchanges', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Insurance - Diversified', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Insurance - Life', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Insurance - Property & Casualty', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Insurance - Reinsurance', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Insurance - Specialty', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Insurance Brokers', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Mortgage Finance', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Shell Companies', 6);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Biotechnology', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Diagnostics & Research', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Drug Manufacturers - General', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Drug Manufacturers - Specialty & Generic', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Health Information Services', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Healthcare Plans', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Medical Care Facilities', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Medical Devices', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Medical Distribution', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Medical Instruments & Supplies', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Pharmaceutical Retailers', 7);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Aerospace & Defense', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Airlines', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Airports & Air Services', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Building Products & Equipment', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Business Equipment & Supplies', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Conglomerates', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Consulting Services', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Electrical Equipment & Parts', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Engineering & Construction', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Farm & Heavy Construction Machinery', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Industrial Distribution', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Integrated Freight & Logistics', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Marine Shipping', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Metal Fabrication', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Pollution & Treatment Controls', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Railroads', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Rental & Leasing Services', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Security & Protection Services', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Specialty Business Services', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Specialty Industrial Machinery', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Staffing & Employment Services', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Tools & Accessories', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Trucking', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Waste Management', 8);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Real Estate - Development', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Real Estate - Diversified', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Real Estate Services', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Diversified', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Healthcare Facilities', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Hotel & Motel', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Industrial', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Mortgage', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Office', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Residential', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Retail', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('REIT - Specialty', 9);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Communication Equipment', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Computer Hardware', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Consumer Electronics', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Electronic Components', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Electronics & Computer Distribution', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Information Technology Services', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Scientific & Technical Instruments', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Semiconductor Equipment & Materials', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Semiconductors', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Software - Application', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Software - Infrastructure', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Solar', 10);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Utilities - Diversified', 11);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Utilities - Independent Power Producers', 11);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Utilities - Regulated Electric', 11);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Utilities - Regulated Gas', 11);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Utilities - Regulated Water', 11);
INSERT INTO `industry`( `name`, `sector_id`) VALUES ('Utilities - Renewable', 11);