CREATE TABLE `stock` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ticker_symbol` varchar(255) NOT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `industry_id` bigint NOT NULL,
  `next_erd` date DEFAULT NULL,
  `next_ert` varchar(255) DEFAULT NULL,
  `next_eeh` varchar(255) DEFAULT NULL,
  `upside_left_percent` decimal(38,2) DEFAULT NULL,
  `last_erd` date DEFAULT NULL,
  `last_eeb` varchar(255) DEFAULT NULL,
  `price` decimal(38,2) DEFAULT NULL,
  `avg_target_price` decimal(38,2) DEFAULT NULL,
  `zacks_rank` int DEFAULT NULL,
  `tip_ranks_score` int DEFAULT NULL,
  `tip_ranks_rating` varchar(255) DEFAULT NULL,
  `ar_buy_count` int DEFAULT '0',
  `hedge_fund_trend` varchar(255) DEFAULT NULL,
  `insider_trade` varchar(255) DEFAULT NULL,
  `huberts_news_sentiment` varchar(255) DEFAULT NULL,
  `news` varchar(255) DEFAULT NULL,
  `huberts_rating` varchar(255) DEFAULT NULL,
  `huberts_remarks` varchar(255) DEFAULT NULL,
  `em_buy_zone` varchar(255) DEFAULT NULL,
  `creation_timestamp` datetime(6) DEFAULT NULL,
  `last_updated_timestamp` datetime(6) DEFAULT NULL,
  `ar_hold_count` int DEFAULT '0',
  `ar_sell_count` int DEFAULT '0',
  `latest_rating_status` varchar(255) DEFAULT NULL,
  `latest_pricing_status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `industry_id` (`industry_id`),
  CONSTRAINT `stock_ibfk_1` FOREIGN KEY (`industry_id`) REFERENCES `industry` (`id`)
) ENGINE=InnoDB ;